import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
  UserButton,
} from "@clerk/nextjs";
import { Header } from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-white">
          <Header />
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <div>
              <SignedOut>
                <SignIn routing="hash" />
              </SignedOut>
              <SignedIn>{children}</SignedIn>
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
